[build-system]

requires = [  # these packages are only required for build purposes, and won't be avaialable after install.
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

# Istructions from : https://packaging.python.org/en/latest/tutorials/packaging-projects/
